language: node_js
node_js: 14.15.5

cache: node_modules

branches:
  only: ['master']

script: npm run build

deploy:
  provider: heroku
  api:key: $HEROKU_API_KEY
  app: limitless-beach-56834
  on:
    branch: master
